### PR TITLE
Add PATCH to CORS allow methods

### PR DESCRIPTION
**Pull request by dougdragon**
This PR adds `PATCH` to the list of CORS allow methods. We're using the docker image and unless I'm mistaken, there's no way to disable CORS support for REST API.

### CODE REVIEW

**Comment by dougdragon** [comment]
@jamesdbloom First PR, be polite 😄

**Comment by jamesdbloom** [comment]
I agree with the change you have made but you need to run the build as some tests are failing with that change.  Alternatively I can make the change and the fix the build directly in the master branch without a PR.  I'm happy either way as you prefer.

**Comment by dougdragon** [comment]
We can't see the test result, if you don't mind making the change that would be great and I'd be happy to close this PR.

**Comment by dougdragon** [comment]
@jamesdbloom Thanks a ton for pushing that change into `master`! We're using the docker image and it's still pulling version `5.3.0` - how can we get an updated docker image?

**Comment by dougdragon** [comment]
Hi @jamesdbloom - is there anything I can do to help with getting a new docker image with [the work you pushed to master](https://github.com/jamesdbloom/mockserver/commit/d730661f523d2f70befb6d5575f67dbc62dd8e6e) from this PR? Happy to do whatever I can to help.

**Comment by jamesdbloom** [comment]
I have added a new tagged version of the MockServer build called mockserver-snapshot so please use that.  I can't due a fully release yet as there are a few more changes due to go into the next release, such as a UI that will show the in-flight requests / expectations and logs, etc.

**Comment by dougdragon** [comment]
@jamesdbloom Thank you very much!

**Pull request closed without merging**
