### PR TITLE
Add Possibility to require basic auth for HTTP proxy mode with a configurable realm

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by jamesdbloom** [comment]
This looks good except there are no unit tests.  Can you please add a unit test for the configuration properties class. And an integration test for the MockServerHandler change.  Once this is done I can merge the PR.

**Comment by Vampire** [comment]
I added setter methods and tests in `ConfigurationPropertiesTest`.
For the integ tests, can you lend me a helping hand and either do it yourself or give me some pointers where to do it / look at?
From a quick look it wasn't obvious to me where and how to test this best.

**Comment by jamesdbloom** [comment]
Ok I'll merge this PR and add an issue to create the integration test.

**Comment by Vampire** [comment]
Nice, thanks

**Pull request merged**
